

name: Python my FastApi web application

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

# permissions:
#   contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build \
          --file Dockerfile \
          --tag hoanganhcoder/testpush:'${{github.sha}}' \
          --push .
    - name : Start api
      run : docker run -d --name testpush -p 80:80 '${{github.sha}}'

    - name : test
      run : curl localhost/
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1